[tools]
dotnet = "latest"
go = "1.26"
java = "openjdk-26"
nim = "2.2.10"
python = "latest"

[env]
EDITOR = "micro"
NUGET_PACKAGES = "~/.local/share/nuget"
DOTNET_CLI_HOME = "~/.local/share/dotnet-cli"
XDG_CONFIG_HOME = "~/.config"
XDG_DATA_HOME = "~/.local/share"
XDG_CACHE_HOME = "~/.cache"
XDG_STATE_HOME = "~/.local/state"
